/* types.js — FINAL STABLE v10 (as previously fixed) */
window.types = Array.isArray(window.types) ? window.types : [];

function addType(){ const input=document.getElementById("typeName"); if(!input) return; const name=(input.value||"").trim(); if(!name) return alert("Enter a valid type name."); if((window.types||[]).some(t=>String(t.name||"").toLowerCase()===name.toLowerCase())) return alert("Type already exists!"); window.types.push({ id: window.uid?window.uid("type"):"type_"+Math.random().toString(36).slice(2,9), name }); if(typeof window.saveTypes==="function") window.saveTypes(); refreshTypesUI(); input.value=""; }
function clearTypes(){ if(!confirm("Delete ALL types?")) return; window.types=[]; if(typeof window.saveTypes==="function") window.saveTypes(); refreshTypesUI(); }
function renderTypes(){ const list=document.getElementById("typeList"); if(!list) return; const types=Array.isArray(window.types)?window.types:[]; if(!types.length){ list.innerHTML="<li>No types added.</li>"; return; } list.innerHTML=types.map(t=>`<li>${(typeof esc==="function")?esc(t.name):String(t.name||"")}</li>`).join(""); }
function updateTypeDropdowns(){ const types=Array.isArray(window.types)?window.types:[]; const stockType=document.getElementById("ptype"); const filterStock=document.getElementById("filterType"); const saleType=document.getElementById("saleType"); const wantType=document.getElementById("wantType"); if(stockType){ stockType.innerHTML=`<option value="">Select</option>` + types.map(t=>`<option value="${(typeof esc==="function")?esc(t.name):String(t.name||"")}">${(typeof esc==="function")?esc(t.name):String(t.name||"")}</option>`).join(""); } if(filterStock){ const cur=filterStock.value||"all"; filterStock.innerHTML=`<option value="all">All Types</option>` + types.map(t=>`<option value="${(typeof esc==="function")?esc(t.name):String(t.name||"")}">${(typeof esc==="function")?esc(t.name):String(t.name||"")}</option>`).join(""); try{ filterStock.value=cur; }catch{} } if(saleType){ const cur=saleType.value||"all"; saleType.innerHTML=`<option value="all">All Types</option>` + types.map(t=>`<option value="${(typeof esc==="function")?esc(t.name):String(t.name||"")}">${(typeof esc==="function")?esc(t.name):String(t.name||"")}</option>`).join(""); try{ saleType.value=cur; }catch{} } if(wantType){ const cur=wantType.value||""; wantType.innerHTML=`<option value="">Select Type</option>` + types.map(t=>`<option value="${(typeof esc==="function")?esc(t.name):String(t.name||"")}">${(typeof esc==="function")?esc(t.name):String(t.name||"")}</option>`).join(""); try{ wantType.value=cur; }catch{} } }
function refreshTypesUI(){ try{ renderTypes(); updateTypeDropdowns(); try{ renderStock?.(); }catch{} try{ renderSales?.(); }catch{} try{ renderWanting?.(); }catch{} }catch(e){console.warn(e);} }

document.addEventListener("click", e => { if(e.target && e.target.id==="addTypeBtn") addType(); if(e.target && e.target.id==="clearTypesBtn") clearTypes(); });
window.addEventListener("load", ()=>{ refreshTypesUI(); });
window.renderTypes = renderTypes; window.updateTypeDropdowns = updateTypeDropdowns;
